import {auth,db} from "./firebase.js";
import {onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,updateProfile} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {collection,doc,getDoc,getDocs,setDoc,addDoc,updateDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
const FAMILY=["families","grandpa-help-demo"],membersRef=collection(db,...FAMILY,"members"),tasksRef=collection(db,...FAMILY,"tasks"),entriesRef=collection(db,...FAMILY,"entries");
const ADMIN_UID="6PEnWw88snMJIg8HKtAh0jAlrME3",APP_URL="https://volodyka-d0e6f.web.app";
const PEOPLE=[{id:"denys",name:"Денис"},{id:"roma",name:"Рома"},{id:"nastya",name:"Настя"}];
const AV={denys:"./assets/denys.png",roma:"./assets/roma.png",nastya:"./assets/nastya.png",grandpa:"./assets/grandpa.png"};
const DEFAULT=[
{id:"clean",name:"Прибирання у дідуся",desc:"Прибирання у дідуся",type:"fixed",rate:15,icon:"🧹"},
{id:"area",name:"Прибирання території",desc:"Прибирання загальної території",type:"fixed",rate:15,icon:"🌿"},
{id:"food",name:"Доставка готової їжі",desc:"Принести готову їжу",type:"fixed",rate:10,icon:"🛒"},
{id:"laundry",name:"Прання та заміна постелі",desc:"Прання та заміна постелі",type:"fixed",rate:15,icon:"🛏️"},
{id:"walk",name:"Прогулянка / час із дідусем",desc:"Прогулянка або час із дідусем",type:"hour",rate:10,icon:"🌲"},
{id:"errand",name:"Додаткова допомога / супровід",desc:"Поїздки, супровід, організаційна допомога",type:"hour",rate:10,icon:"🔧"},
{id:"physical",name:"Додаткове прибирання / фізична робота",desc:"Додаткова фізична робота",type:"hour",rate:15,icon:"🪚"}];
const S={user:null,profile:null,isAdmin:false,tasks:[],entries:[],members:[],selectedTask:null,selectedPerson:"denys",filter:"all",period:"month",screen:"home",adminTab:"members",theme:localStorage.getItem("pflege-theme")||"dark",lang:localStorage.getItem("pflege-lang")||"uk",installPrompt:null};
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const money=n=>Number(n||0).toLocaleString(S.lang==="de"?"de-DE":"uk-UA",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";
const dval=v=>{if(v?.toDate)return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?new Date():d};
const date=v=>dval(v).toLocaleDateString(S.lang==="de"?"de-DE":"uk-UA",{day:"2-digit",month:"short",year:"numeric"});
const today=()=>{const d=new Date(),z=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`};
function toast(t){const x=$("toast");x.textContent=t;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),2800)}
function avatar(id,cls="avatar sm"){return `<span class="${cls}" style="background-image:url('${AV[id]||AV.roma}')"></span>`}
function avatarId(name){const n=String(name||"").toLowerCase();if(n.includes("наст")||n.includes("nast"))return"nastya";if(n.includes("ром")||n.includes("rom"))return"roma";if(n.includes("ден")||n.includes("den"))return"denys";return"roma"}
function status(e){return e.paid?"paid":e.status==="approved"?"approved":"pending"}
function statusText(e){return e.paid?"Виплачено":e.status==="approved"?"Підтверджено":"Очікує"}
function normalize(id,e){const base=Number(e.base||0),bonus=Number(e.bonus||0);return{id,...e,base,bonus,total:Number(e.total??base+bonus),paid:Boolean(e.paid),status:e.status||"pending"}}
async function seed(){if(!S.isAdmin)return;const snap=await getDocs(tasksRef);if(snap.empty)for(const t of DEFAULT)await setDoc(doc(tasksRef,t.id),{...t,active:true,createdAt:serverTimestamp(),createdBy:ADMIN_UID})}
async function loadProfile(){const r=doc(membersRef,S.user.uid),s=await getDoc(r);if(s.exists())S.profile={id:s.id,...s.data()};else{S.profile={id:S.user.uid,name:S.user.displayName||S.user.email,email:S.user.email,role:S.isAdmin?"admin":"participant",active:true,avatarId:avatarId(S.user.displayName)};await setDoc(r,{name:S.profile.name,email:S.profile.email,role:S.profile.role,active:true,avatarId:S.profile.avatarId,createdAt:serverTimestamp()})}if(S.isAdmin&&S.profile.role!=="admin"){await updateDoc(r,{role:"admin"});S.profile.role="admin"}}
async function load(){const [ts,es]=await Promise.all([getDocs(tasksRef),getDocs(entriesRef)]);S.tasks=ts.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false).sort((a,b)=>String(a.name).localeCompare(String(b.name)));S.entries=es.docs.map(d=>normalize(d.id,d.data())).sort((a,b)=>dval(b.createdAt||b.date)-dval(a.createdAt||a.date));if(S.isAdmin){const ms=await getDocs(membersRef);S.members=ms.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.name||"").localeCompare(String(b.name||"")))}else S.members=[]}
function myEntries(){return S.entries.filter(e=>e.uid===S.user.uid)}
function monthEntries(){const now=new Date(),start=new Date(now);if(S.period==="month")start.setDate(1);if(S.period==="quarter")start.setMonth(Math.floor(now.getMonth()/3)*3,1);if(S.period==="year")start.setMonth(0,1);start.setHours(0,0,0,0);return S.entries.filter(e=>{const d=dval(e.date);return d>=start&&d<=now})}
function renderHome(){const es=myEntries(),now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1),m=es.filter(e=>dval(e.date)>=start&&dval(e.date)<=now),total=m.reduce((s,e)=>s+e.total,0),paid=m.filter(e=>e.paid).reduce((s,e)=>s+e.total,0);$("homeName").textContent=S.profile?.name||"—";$("homeAvatar").style=`background-image:url('${AV[S.profile?.avatarId||avatarId(S.profile?.name)]||AV.roma}')`;$("homeTotal").textContent=money(total);$("homePaid").textContent=money(paid);$("homeDue").textContent=money(total-paid);$("homeRecent").innerHTML=es.slice(0,4).map(workRow).join("")||empty("Поки немає записів.")}
function workRow(e,admin=false){const id=avatarId(e.child);return `<div class="work-row">${avatar(id,"avatar sm")}<div class="row-main"><b>${esc(e.child||"—")}</b><small>${esc(e.taskName||"—")} · ${date(e.date)}</small><span class="status ${status(e)}">${statusText(e)}</span></div><div class="row-end">${money(e.total)}${e.hours?`<small>${esc(e.hours)} год</small>`:""}${admin?`<div class="admin-actions"><button class="mini" data-approve="${e.id}" ${e.status==="approved"?"disabled":""}>✓</button><button class="mini" data-bonus="${e.id}">＋</button><button class="mini" data-paid="${e.id}" ${!e.paid&&e.status!=="approved"?"disabled":""}>${e.paid?"↶":"€"}</button></div>`:""}</div></div>`}
function empty(t){return `<div class="card" style="text-align:center;color:var(--muted);padding:24px">${esc(t)}</div>`}
function renderTasks(){const mine=myEntries().map(e=>e.taskId);$("tasksList").innerHTML=S.tasks.map(t=>`<button class="task-row" data-task="${esc(t.id)}"><span class="task-icon">${esc(t.icon||"✓")}</span><span class="row-main"><b>${esc(t.name)}</b><small>${esc(t.desc||"")}</small></span><span class="row-end">${money(t.rate)}${t.type==="hour"?"<small>/год</small>":""}</span></button>`).join("")||empty("Завдань поки немає.")}
function renderAdd(){$("peoplePicker").innerHTML=PEOPLE.map(p=>`<button class="person ${S.selectedPerson===p.id?"active":""}" data-person="${p.id}">${avatar(p.id,"avatar") }<b>${p.name}</b></button>`).join("");if(!S.selectedTask){$("selectedTaskCard").innerHTML=`<button data-open-tasks>＋&nbsp; Обрати завдання</button>`}else{$("selectedTaskCard").innerHTML=`<button data-open-tasks><span class="task-icon">${esc(S.selectedTask.icon||"✓")}</span><span><b>${esc(S.selectedTask.name)}</b><small>${money(S.selectedTask.rate)}${S.selectedTask.type==="hour"?" / год":""}</small></span></button>`;$(`hoursWrap`).hidden=S.selectedTask.type!=="hour";$(`workTotal`).textContent=money(S.selectedTask.rate*(S.selectedTask.type==="hour"?Number($("hours").value||0):1))}}
function renderHistory(){let es=myEntries();if(S.filter==="pending")es=es.filter(e=>!e.paid&&e.status!=="approved");if(S.filter==="approved")es=es.filter(e=>e.status==="approved"&&!e.paid);if(S.filter==="paid")es=es.filter(e=>e.paid);$("historyList").innerHTML=es.map(workRow).join("")||empty("Поки немає записів.")}
function renderReports(){const es=monthEntries(),total=es.reduce((s,e)=>s+e.total,0),paid=es.filter(e=>e.paid).reduce((s,e)=>s+e.total,0);$("rTotal").textContent=money(total);$("rPaid").textContent=money(paid);$("rDue").textContent=money(total-paid);$("rCount").textContent=es.length;const g={};for(const e of es)g[e.child||"—"]=(g[e.child||"—"]||0)+e.total;const max=Math.max(1,...Object.values(g));$("rMembers").innerHTML=Object.entries(g).map(([n,v])=>`<div class="member-row">${avatar(avatarId(n),"avatar sm")}<div class="row-main"><b>${esc(n)}</b><small>${money(v)}</small><div class="progress"><i style="width:${Math.round(v/max*100)}%"></i></div></div><div class="row-end">${money(v)}</div></div>`).join("")||empty("Немає робіт за період.")}
function renderProfile(){const p=S.profile||{},aid=p.avatarId||avatarId(p.name),es=myEntries(),total=es.reduce((s,e)=>s+e.total,0),paid=es.filter(e=>e.paid).reduce((s,e)=>s+e.total,0);$("profileAvatar").style=`background-image:url('${AV[aid]||AV.roma}')`;$(`profileName`).textContent=p.name||"—";$(`profileRole`).textContent=S.isAdmin?"Адміністратор":"Учасник";$(`profileEmail`).textContent=p.email||S.user?.email||"—";$(`profileRole2`).textContent=S.isAdmin?"Адміністратор":"Учасник";$(`profileStats`).innerHTML=`<div><small>Робіт</small><b>${es.length}</b></div><div><small>Зароблено</small><b>${money(total)}</b></div><div><small>Виплачено</small><b>${money(paid)}</b></div><div><small>До виплати</small><b>${money(total-paid)}</b></div>`;$(`avatarPicker`).innerHTML=["denys","roma","nastya","grandpa"].map(id=>`<button class="avatar-option ${id===aid?"active":""}" data-avatar="${id}">${avatar(id,"avatar")}</button>`).join("");$("profileBtn").style=`background-image:url('${AV[aid]||AV.roma}')`;$(`drawerUser`).innerHTML=`<b>${esc(p.name||"—")}</b><small>${esc(p.email||"")}</small>`}
function renderAdmin(){if(!S.isAdmin)return;const es=S.entries,total=es.reduce((s,e)=>s+e.total,0),paid=es.filter(e=>e.paid).reduce((s,e)=>s+e.total,0),pending=es.filter(e=>!e.paid&&e.status!=="approved").length;$(`adminStats`).innerHTML=`<div><small>Загальна сума</small><b>${money(total)}</b></div><div><small>Виплачено</small><b>${money(paid)}</b></div><div><small>До виплати</small><b>${money(total-paid)}</b></div><div><small>Очікують</small><b>${pending}</b></div>`;document.querySelectorAll("[data-admin]").forEach(x=>x.classList.toggle("active",x.dataset.admin===S.adminTab));if(S.adminTab==="members")$("adminPanel").innerHTML=`<div class="card">${S.members.map(m=>`<div class="member-row">${avatar(m.avatarId||avatarId(m.name),"avatar sm")}<div class="row-main"><b>${esc(m.name||"—")}</b><small>${esc(m.email||"")}</small></div><span class="chip">${m.role==="admin"?"ADMIN":"✓"}</span></div>`).join("")||empty("Немає учасників.")}</div>`;if(S.adminTab==="tasks")renderAdminTasks();if(S.adminTab==="works")$("adminPanel").innerHTML=`<div class="list">${S.entries.map(e=>workRow(e,true)).join("")||empty("Немає робіт.")}</div>`}
function renderAdminTasks(){$("adminPanel").innerHTML=`<div class="card"><h3>Додати завдання</h3><div class="admin-form"><input id="tn" placeholder="Назва"><input id="td" placeholder="Опис"><select id="tt"><option value="fixed">Фіксована сума</option><option value="hour">Погодинна оплата</option></select><input id="tr" type="number" min="0" step="0.5" value="10"><button id="addTask" class="btn gold">＋ Створити</button></div></div><div class="card">${S.tasks.map(t=>`<div class="member-row"><span class="task-icon">${esc(t.icon||"✓")}</span><div class="row-main"><b>${esc(t.name)}</b><small>${money(t.rate)} · ${t.type==="hour"?"/год":"fixed"}</small></div><button class="mini" data-edit-task="${t.id}">✎</button></div>`).join("")}</div>`;$("addTask").onclick=async()=>{const name=$("tn").value.trim(),desc=$("td").value.trim(),type=$("tt").value,rate=Number($("tr").value);if(!name||!Number.isFinite(rate)||rate<0)return toast("Заповніть назву і суму.");await addDoc(tasksRef,{name,desc,type,rate,icon:"✓",active:true,createdAt:serverTimestamp(),createdBy:S.user.uid});await refresh();S.adminTab="tasks";renderAdmin()};document.querySelectorAll("[data-edit-task]").forEach(b=>b.onclick=()=>editTask(b.dataset.editTask))}
async function editTask(id){const t=S.tasks.find(x=>x.id===id);if(!t)return;const name=prompt("Назва",t.name);if(name===null)return;const rate=Number(prompt("Сума / ставка",t.rate));if(!name.trim()||!Number.isFinite(rate)||rate<0)return toast("Некоректні дані.");await updateDoc(doc(tasksRef,id),{name:name.trim(),rate});await refresh();S.adminTab="tasks";renderAdmin()}
function renderAll(){if(!S.user)return;renderHome();renderTasks();renderAdd();renderHistory();renderReports();renderProfile();renderAdmin();}
function screen(id){if(id==="admin"&&!S.isAdmin)return toast("Доступно лише адміністратору.");S.screen=id;document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("screen-"+id)?.classList.add("active");document.querySelectorAll("[data-screen]").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));window.scrollTo({top:0,behavior:"smooth"});closeMenu()}
function openTask(id){const t=S.tasks.find(x=>x.id===id);if(!t)return;S.selectedTask=t;renderAdd();screen("add")}
async function saveWork(){if(!S.selectedTask)return toast("Спочатку оберіть завдання.");const t=S.selectedTask,h=t.type==="hour"?Number($("hours").value):null;if(t.type==="hour"&&(!Number.isFinite(h)||h<=0))return toast("Вкажіть кількість годин.");const base=Number(t.rate||0)*(h||1);const child=PEOPLE.find(p=>p.id===S.selectedPerson)?.name||S.profile.name;try{$("saveWork").disabled=true;await addDoc(entriesRef,{uid:S.user.uid,child,taskId:t.id,taskName:t.name,hours:h,base,bonus:0,total:base,paid:false,status:"pending",date:new Date(`${$("workDate").value||today()}T12:00:00`).toISOString(),createdAt:serverTimestamp()});await refresh();S.selectedTask=null;screen("home");toast("Роботу додано. Вона очікує підтвердження адміністратора.")}catch(e){console.error(e);toast("Не вдалося зберегти роботу.")}finally{$("saveWork").disabled=false}}
async function approve(id){if(!S.isAdmin)return;await updateDoc(doc(entriesRef,id),{status:"approved"});await refresh();renderAdmin();toast("Роботу підтверджено.")}
async function bonus(id){if(!S.isAdmin)return;const e=S.entries.find(x=>x.id===id),v=prompt("Бонус у євро",String(e?.bonus||0));if(v===null)return;const b=Number(v);if(!Number.isFinite(b)||b<0)return toast("Некоректний бонус.");await updateDoc(doc(entriesRef,id),{bonus:b,total:Number(e.base||0)+b,status:"approved"});await refresh();renderAdmin();toast("Бонус збережено.")}
async function paid(id){if(!S.isAdmin)return;const e=S.entries.find(x=>x.id===id);if(!e)return;if(!e.paid&&e.status!=="approved")return toast("Спочатку підтвердьте роботу.");await updateDoc(doc(entriesRef,id),{paid:!e.paid});await refresh();renderAdmin();toast(e.paid?"Виплату скасовано.":"Позначено як виплачено.")}
async function selectAvatar(id){await updateDoc(doc(membersRef,S.user.uid),{avatarId:id});S.profile.avatarId=id;renderProfile();toast("Аватар оновлено.")}
async function login(){try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(e){$("loginError").textContent="Неправильний E-Mail або пароль.";$("loginError").hidden=false}}
async function register(){const n=$("regName").value.trim(),em=$("regEmail").value.trim(),p=$("regPass").value;if(!n||!em||p.length<6||p!==$("regPass2").value)return showError("regError","Перевірте ім'я, E-Mail і пароль.");try{const c=await createUserWithEmailAndPassword(auth,em,p);await updateProfile(c.user,{displayName:n});await setDoc(doc(membersRef,c.user.uid),{name:n,email:em,role:"participant",active:true,avatarId:avatarId(n),createdAt:serverTimestamp()})}catch(e){showError("regError",e.code==="auth/email-already-in-use"?"Цей E-Mail уже зареєстрований.":"Не вдалося створити акаунт.")}}
function showError(id,t){$(id).textContent=t;$(id).hidden=false}
async function refresh(){await seed();await load();renderAll()}
function theme(t){S.theme=t;localStorage.setItem("pflege-theme",t);document.documentElement.dataset.theme=t;$("darkMode").classList.toggle("active",t==="dark");$("lightMode").classList.toggle("active",t==="light")}
async function shareText(){const es=monthEntries(),total=es.reduce((s,e)=>s+e.total,0),paid=es.filter(e=>e.paid).reduce((s,e)=>s+e.total,0),text=`PFLEGE — Допомога дідусеві
Разом: ${money(total)}
Виплачено: ${money(paid)}
До виплати: ${money(total-paid)}
Робіт: ${es.length}`;try{if(navigator.share)await navigator.share({title:"PFLEGE",text});else{await navigator.clipboard.writeText(text);toast("Звіт скопійовано — можна надіслати у Viber.")}}catch(e){if(e.name!=="AbortError")toast("Не вдалося поділитися звітом.")}}
async function shareApp(){try{if(navigator.share)await navigator.share({title:"PFLEGE — Допомога дідусеві",text:"PFLEGE",url:APP_URL});else{await navigator.clipboard.writeText(APP_URL);toast("Посилання скопійовано.")}}catch(e){if(e.name!=="AbortError")toast(APP_URL)}}
async function install(){if(S.installPrompt){S.installPrompt.prompt();await S.installPrompt.userChoice;S.installPrompt=null}else toast("Відкрийте меню браузера та оберіть «Встановити застосунок».")}
function closeMenu(){$("menu").hidden=true}function openMenu(){$("menu").hidden=false}
// events
$("openRegister").onclick=()=>{$("loginCard").hidden=true;$(`registerCard`).hidden=false};$("backLogin").onclick=()=>{$("loginCard").hidden=false;$(`registerCard`).hidden=true};$("loginBtn").onclick=login;$("regBtn").onclick=register;$("loginPassword").onkeydown=e=>e.key==="Enter"&&login();
$("homeBtn").onclick=()=>screen("home");$("profileBtn").onclick=()=>screen("profile");$("menuBtn").onclick=openMenu;$("bottomMenu").onclick=openMenu;$("closeMenu").onclick=closeMenu;$("drawerBack").onclick=closeMenu;$("homeAdd").onclick=()=>screen("add");$("saveWork").onclick=saveWork;$("hoursMinus").onclick=()=>{$("hours").value=Math.max(.25,Number($("hours").value||1)-.25);renderAdd()};$("hoursPlus").onclick=()=>{$("hours").value=Number($("hours").value||1)+.25;renderAdd()};$("hours").oninput=renderAdd;$("workDate").value=today();
$("reportPeriod").onchange=()=>{S.period=$("reportPeriod").value;renderReports()};$("shareReport").onclick=shareText;$("shareApp").onclick=shareApp;$("installApp").onclick=install;$("installSettings").onclick=install;$("logout").onclick=()=>signOut(auth);$("editProfile").onclick=()=>{$("editName").value=S.profile?.name||"";$(`profileModal`).hidden=false};document.querySelectorAll("[data-close-profile]").forEach(x=>x.onclick=()=>$("profileModal").hidden=true);$("saveName").onclick=async()=>{const n=$("editName").value.trim();if(!n)return;await updateProfile(S.user,{displayName:n});await updateDoc(doc(membersRef,S.user.uid),{name:n});S.profile.name=n;$("profileModal").hidden=true;renderAll();toast("Профіль збережено.")};
$("darkMode").onclick=()=>theme("dark");$("lightMode").onclick=()=>theme("light");$("uaMode").onclick=()=>{S.lang="uk";localStorage.setItem("pflege-lang","uk");location.reload()};$("deMode").onclick=()=>{S.lang="de";localStorage.setItem("pflege-lang","de");location.reload()};$("langBtn").onclick=()=>{S.lang=S.lang==="uk"?"de":"uk";localStorage.setItem("pflege-lang",S.lang);location.reload()};document.querySelectorAll("[data-auth-lang]").forEach(b=>b.onclick=()=>{S.lang=b.dataset.authLang;localStorage.setItem("pflege-lang",S.lang);location.reload()});
document.addEventListener("click",e=>{const s=e.target.closest("[data-screen]");if(s&&!e.target.closest(".bottom")){screen(s.dataset.screen);return}const t=e.target.closest("[data-task]");if(t)openTask(t.dataset.task);const p=e.target.closest("[data-person]");if(p){S.selectedPerson=p.dataset.person;renderAdd()}const a=e.target.closest("[data-avatar]");if(a)selectAvatar(a.dataset.avatar);if(e.target.closest("[data-open-tasks]"))screen("tasks");const f=e.target.closest("[data-filter]");if(f){S.filter=f.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));f.classList.add("active");renderHistory()}const ad=e.target.closest("[data-admin]");if(ad){S.adminTab=ad.dataset.admin;renderAdmin()}const ap=e.target.closest("[data-approve]");if(ap)approve(ap.dataset.approve);const bo=e.target.closest("[data-bonus]");if(bo)bonus(bo.dataset.bonus);const pa=e.target.closest("[data-paid]");if(pa)paid(pa.dataset.paid);});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();S.installPrompt=e});window.addEventListener("appinstalled",()=>{S.installPrompt=null;toast("PFLEGE встановлено.")});
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(console.warn);theme(S.theme);
onAuthStateChanged(auth,async user=>{S.user=user;if(!user){$("authView").hidden=false;$("appView").hidden=true;return}S.isAdmin=user.uid===ADMIN_UID;$("authView").hidden=true;$("appView").hidden=false;try{await loadProfile();await refresh();$("adminLink").hidden=!S.isAdmin;screen("home")}catch(e){console.error(e);toast("Не вдалося завантажити Firebase-дані.")}});
