import { auth, db } from "./firebase.js";
import { onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, updateProfile } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
const FAMILY=["families","grandpa-help-demo"],membersRef=collection(db,...FAMILY,"members"),tasksRef=collection(db,...FAMILY,"tasks"),entriesRef=collection(db,...FAMILY,"entries");
const ADMIN_UID="6PEnWw88snMJIg8HKtAh0jAlrME3";
const DEFAULT_TASKS=[
{id:"clean",name:"🧹 Прибирання у дідуся",desc:"Прибирання у дідуся",type:"fixed",rate:15},
{id:"area",name:"🌿 Прибирання території",desc:"Прибирання спільної території",type:"fixed",rate:15},
{id:"food",name:"🛒 Доставка продуктів",desc:"Принести готову їжу",type:"fixed",rate:10},
{id:"laundry",name:"🛏 Прання та заміна постелі",desc:"Прання та заміна білизни",type:"fixed",rate:15},
{id:"walk",name:"🌳 Прогулянка / час із дідусем",desc:"Прогулянка або час із дідусем",type:"hour",rate:10},
{id:"errand",name:"🔧 Додаткова допомога",desc:"Поїздка, супровід або організаційна справа",type:"hour",rate:10},
{id:"physical",name:"🪚 Додаткова фізична робота",desc:"Додаткова фізична робота",type:"hour",rate:15}
];
const AVATARS={
  grandpa:{label:"Володимир",bg:"#ead7bd",svg:`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'><rect width='200' height='200' rx='100' fill='#ead7bd'/><path fill='#30443a' d='M38 190c2-50 28-73 62-73s60 23 62 73'/><path fill='#d2a27a' d='M55 83c0-40 20-61 45-61s45 21 45 61v38c0 28-20 47-45 47s-45-19-45-47z'/><path fill='#e8e1d6' d='M52 69c4-40 22-55 49-55 27 0 45 15 49 55-12-12-29-18-49-18S64 57 52 69'/><path fill='#76543d' d='M75 91h20v4H75zm30 0h20v4h-20z'/><circle cx='85' cy='101' r='4' fill='#30261f'/><circle cx='115' cy='101' r='4' fill='#30261f'/><path d='M100 102v19l-7 6' fill='none' stroke='#815b43' stroke-width='4' stroke-linecap='round'/><path fill='#ded6cb' d='M72 128c9-10 18-7 28 0 10-7 19-10 28 0-6 15-17 20-28 20s-22-5-28-20'/><path d='M91 151c6 4 12 4 18 0' fill='none' stroke='#6f4d3a' stroke-width='4' stroke-linecap='round'/></svg>`},
  denys:{label:"Денис",bg:"#d8c2aa",svg:`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'><rect width='200' height='200' rx='100' fill='#d8c2aa'/><path fill='#202724' d='M33 190c4-49 30-73 67-73s63 24 67 73'/><path fill='#d8a67f' d='M52 79c0-39 21-59 48-59s48 20 48 59v43c0 28-20 47-48 47s-48-19-48-47z'/><path fill='#dedbd4' d='M48 72c4-44 24-60 52-60s48 16 52 60c-17-13-35-18-52-18S65 59 48 72'/><path fill='#7b5b48' d='M68 93h23v4H68zm41 0h23v4h-23z'/><circle cx='80' cy='103' r='4' fill='#2b211d'/><circle cx='120' cy='103' r='4' fill='#2b211d'/><path d='M100 105v17l-6 5' fill='none' stroke='#805a43' stroke-width='4' stroke-linecap='round'/><path fill='#b77c58' d='M76 129c7-5 14-5 24 2 10-7 17-7 24-2-4 12-13 20-24 20s-20-8-24-20'/><path d='M86 151c8 4 20 4 28 0' fill='none' stroke='#5d3d30' stroke-width='4' stroke-linecap='round'/></svg>`},
  roma:{label:"Рома",bg:"#caa98d",svg:`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'><rect width='200' height='200' rx='100' fill='#caa98d'/><path fill='#26302e' d='M40 190c3-46 27-69 60-69s57 23 60 69'/><path fill='#e0b08c' d='M57 78c0-34 19-55 43-55s43 21 43 55v48c0 25-18 43-43 43s-43-18-43-43z'/><path fill='#8d705f' d='M51 78c2-44 19-62 49-62 29 0 46 18 49 62-11-14-27-24-49-24-21 0-38 10-49 24'/><path fill='#8d705f' d='M56 70c8-6 17-13 25-20 10 9 23 13 39 15 10 1 19 5 28 13v17c-12-11-26-16-42-16-20 0-36-4-50-9z'/><circle cx='82' cy='103' r='4' fill='#2b2522'/><circle cx='118' cy='103' r='4' fill='#2b2522'/><path d='M88 130c8 6 16 6 24 0' fill='none' stroke='#875e4b' stroke-width='4' stroke-linecap='round'/></svg>`},
  nastya:{label:"Настя",bg:"#d8b49e",svg:`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'><rect width='200' height='200' rx='100' fill='#d8b49e'/><path fill='#46554a' d='M35 190c5-49 30-72 65-72s60 23 65 72'/><path fill='#f0c0a0' d='M56 78c0-34 19-56 44-56s44 22 44 56v48c0 25-18 43-44 43s-44-18-44-43z'/><path fill='#9b563c' d='M50 91c-4-45 17-73 50-73 33 0 54 28 50 73l-17-25c-10 17-25 28-45 34-15-7-27-17-38-34z'/><path fill='#9b563c' d='M48 73c-2 35 4 56 18 69-21-4-28-31-18-69zm104 0c2 35-4 56-18 69 21-4 28-31 18-69z'/><circle cx='83' cy='104' r='4' fill='#2b2522'/><circle cx='117' cy='104' r='4' fill='#2b2522'/><path d='M88 131c8 6 16 6 24 0' fill='none' stroke='#8b5947' stroke-width='4' stroke-linecap='round'/></svg>`}
};
const I18N={
uk:{subtitle:"Допомога дідусеві",familyCare:"СІМЕЙНА ТУРБОТА",welcomeText:"Разом допомагаємо. Разом піклуємося.",login:"ВХІД",welcomeBack:"Раді бачити знову",password:"Пароль",loginButton:"Увійти",createAccount:"Створити акаунт",registration:"РЕЄСТРАЦІЯ",name:"Ім'я",repeatPassword:"Повторіть пароль",registerButton:"Зареєструватися",back:"Назад",hello:"Привіт",thankYou:"Дякуємо, що ти поруч ❤️",together:"Разом допомагаємо дідусеві",togetherText:"Кожна маленька допомога має значення.",thisMonth:"ЦЬОГО МІСЯЦЯ",toPay:"До виплати",paid:"Виплачено",addWork:"Додати роботу",quick:"ШВИДКО",tasks:"Завдання",all:"Усі",latest:"ОСТАННЄ",activity:"Активність",work:"Робота",hours:"Кількість годин",date:"Дата",noteOptional:"Примітка (необов'язково)",total:"Разом",saveWork:"Додати роботу",pendingNote:"Після додавання робота очікує підтвердження адміністратора.",myRecords:"МОЇ ЗАПИСИ",history:"Історія",pending:"Очікує",approved:"Підтверджено",overview:"ОГЛЯД",reports:"Звіти",month:"Місяць",quarter:"Квартал",year:"Рік",overall:"Загальна сума",worksCount:"Кількість робіт",byMembers:"По учасниках",shareReport:"Поділитися звітом",chooseAvatar:"Мій аватар",role:"Роль",logout:"Вийти",admin:"Адміністратор",members:"Учасники",worksPayments:"Роботи",sharePlege:"Поділитися PFLEGE",scanQr:"Скануйте QR-код камерою телефону",qrText:"Відкриється PFLEGE, після чого застосунок можна встановити на телефон.",share:"Поділитися",install:"Встановити PFLEGE",settingsSmall:"ПЕРСОНАЛІЗАЦІЯ",settings:"Налаштування",theme:"Тема",language:"Мова",profile:"Профіль",editProfile:"Редагувати профіль",save:"Зберегти",oneLastStep:"ЩЕ ОДИН КРОК",chooseYourself:"Обери свій аватар",avatarText:"Обери образ, у якому ти себе впізнаєш.",continue:"Продовжити",noWork:"Поки немає записів.",noTasks:"Завдань поки немає.",confirm:"Підтвердити",bonus:"Бонус",paidAction:"Виплачено",cancelPaid:"Скасувати",waiting:"Очікує підтвердження",statusApproved:"Підтверджено",statusPaid:"Виплачено",adminOnly:"Доступно адміністратору",membersCount:"учасників",totalLabel:"Разом",dueLabel:"До виплати",workLabel:"робіт",earned:"зароблено",installHint:"Додайте PFLEGE на головний екран телефону."},
de:{subtitle:"Hilfe für Opa",familyCare:"FAMILIENHILFE",welcomeText:"Gemeinsam helfen. Gemeinsam kümmern.",login:"ANMELDUNG",welcomeBack:"Schön, dass du wieder da bist",password:"Passwort",loginButton:"Anmelden",createAccount:"Konto erstellen",registration:"REGISTRIERUNG",name:"Name",repeatPassword:"Passwort wiederholen",registerButton:"Registrieren",back:"Zurück",hello:"Hallo",thankYou:"Danke, dass du da bist ❤️",together:"Gemeinsam helfen wir Opa",togetherText:"Jede kleine Hilfe zählt.",thisMonth:"DIESEN MONAT",toPay:"Offen",paid:"Ausgezahlt",addWork:"Arbeit hinzufügen",quick:"SCHNELL",tasks:"Aufgaben",all:"Alle",latest:"NEUESTES",activity:"Aktivität",work:"Arbeit",hours:"Stunden",date:"Datum",noteOptional:"Notiz (optional)",total:"Gesamt",saveWork:"Arbeit hinzufügen",pendingNote:"Nach dem Hinzufügen wartet der Eintrag auf die Bestätigung des Administrators.",myRecords:"MEINE EINTRÄGE",history:"Verlauf",pending:"Offen",approved:"Bestätigt",overview:"ÜBERSICHT",reports:"Berichte",month:"Monat",quarter:"Quartal",year:"Jahr",overall:"Gesamtsumme",worksCount:"Arbeiten",byMembers:"Nach Mitgliedern",shareReport:"Bericht teilen",chooseAvatar:"Mein Avatar",role:"Rolle",logout:"Abmelden",admin:"Administrator",members:"Mitglieder",worksPayments:"Arbeiten",sharePlege:"PFLEGE teilen",scanQr:"QR-Code mit der Handykamera scannen",qrText:"PFLEGE wird geöffnet und kann anschließend auf dem Telefon installiert werden.",share:"Teilen",install:"PFLEGE installieren",settingsSmall:"PERSONALISIERUNG",settings:"Einstellungen",theme:"Design",language:"Sprache",profile:"Profil",editProfile:"Profil bearbeiten",save:"Speichern",oneLastStep:"NOCH EIN SCHRITT",chooseYourself:"Wähle deinen Avatar",avatarText:"Wähle das Bild, in dem du dich wiedererkennst.",continue:"Weiter",noWork:"Noch keine Einträge.",noTasks:"Noch keine Aufgaben.",confirm:"Bestätigen",bonus:"Bonus",paidAction:"Ausgezahlt",cancelPaid:"Stornieren",waiting:"Wartet auf Bestätigung",statusApproved:"Bestätigt",statusPaid:"Ausgezahlt",adminOnly:"Nur für Administratoren",membersCount:"Mitglieder",totalLabel:"Gesamt",dueLabel:"Offen",workLabel:"Arbeiten",earned:"verdient",installHint:"PFLEGE zum Startbildschirm hinzufügen."}
};
const state={user:null,profile:null,isAdmin:false,tasks:[],mine:[],allEntries:[],members:[],selectedTask:null,historyFilter:"all",reportPeriod:"month",adminTab:"members",lang:localStorage.getItem("pflege-lang")||"uk",theme:localStorage.getItem("pflege-theme")||"dark",installPrompt:null,onboardingAvatar:null,currentScreen:"home"};
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const money=n=>Number(n||0).toLocaleString(state.lang==="de"?"de-DE":"uk-UA",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";
const dateObj=v=>{if(!v)return new Date();if(v.toDate)return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?new Date():d};
const formatDate=v=>dateObj(v).toLocaleDateString(state.lang==="de"?"de-DE":"uk-UA",{day:"2-digit",month:"short",year:"numeric"});
const formatDateTime=v=>dateObj(v).toLocaleString(state.lang==="de"?"de-DE":"uk-UA",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});
const todayISO=()=>{const d=new Date();const z=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`};
const avatarStyle=id=>`background-image:url("data:image/svg+xml,${encodeURIComponent(AVATARS[id]?.svg||AVATARS.roma.svg)}")`;
function applyTheme(){document.documentElement.dataset.theme=state.theme;$("themeDark")?.classList.toggle("active",state.theme==="dark");$("themeLight")?.classList.toggle("active",state.theme==="light");document.querySelector('meta[name="theme-color"]').setAttribute("content",state.theme==="dark"?"#17110d":"#f4ede2")}
function applyLanguage(){document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;if(I18N[state.lang][key])el.textContent=I18N[state.lang][key]});$("authLangUa")?.classList.toggle("active",state.lang==="uk");$("authLangDe")?.classList.toggle("active",state.lang==="de");$("langUa")?.classList.toggle("active",state.lang==="uk");$("langDe")?.classList.toggle("active",state.lang==="de");renderAll()}
function setLanguage(lang){state.lang=lang;localStorage.setItem("pflege-lang",lang);applyLanguage()}
function showToast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),2800)}
function authMode(mode){$("loginCard").hidden=mode!=="login";$("registerCard").hidden=mode!=="register"}
function errorBox(id,msg){$(id).textContent=msg;$(id).hidden=false}
function clearErrors(){$("loginError").hidden=true;$('registerError').hidden=true}
async function login(){clearErrors();try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(e){errorBox("loginError",e.code==="auth/invalid-credential"?(state.lang==="de"?"E-Mail oder Passwort ist falsch.":"Неправильний E-Mail або пароль."):(state.lang==="de"?"Anmeldung fehlgeschlagen.":"Не вдалося увійти."))}}
async function register(){clearErrors();const name=$("registerName").value.trim(),email=$("registerEmail").value.trim(),pass=$("registerPassword").value,pass2=$("registerPassword2").value;if(!name||!email||pass.length<6||pass!==pass2){errorBox("registerError",state.lang==="de"?"Bitte Name, E-Mail und Passwort prüfen.":"Перевірте ім'я, E-Mail і пароль (мінімум 6 символів). ");return}try{const c=await createUserWithEmailAndPassword(auth,email,pass);await updateProfile(c.user,{displayName:name});await setDoc(doc(membersRef,c.user.uid),{name,email,role:"participant",active:true,avatarId:null,createdAt:serverTimestamp()});state.onboardingAvatar=null}catch(e){errorBox("registerError",e.code==="auth/email-already-in-use"?(state.lang==="de"?"Diese E-Mail ist bereits registriert.":"Цей E-Mail уже зареєстрований."):(state.lang==="de"?"Konto konnte nicht erstellt werden.":"Не вдалося створити акаунт."))}}
async function loadProfile(){const ref=doc(membersRef,state.user.uid),snap=await getDoc(ref);if(snap.exists())state.profile={id:snap.id,...snap.data()};else{state.profile={id:state.user.uid,name:state.user.displayName||state.user.email,email:state.user.email,role:state.isAdmin?"admin":"participant",active:true,avatarId:resolveAvatarId(state.user.displayName)};await setDoc(ref,{name:state.profile.name,email:state.profile.email,role:state.profile.role,active:true,avatarId:state.profile.avatarId,createdAt:serverTimestamp()})}if(state.isAdmin&&state.profile.role!=="admin"){await updateDoc(ref,{role:"admin"});state.profile.role="admin"}}
async function ensureDefaultTasks(){const snap=await getDocs(tasksRef);if(snap.empty&&state.isAdmin){for(const t of DEFAULT_TASKS)await setDoc(doc(tasksRef,t.id),{...t,active:true,createdAt:serverTimestamp(),createdBy:ADMIN_UID})}}
async function loadData(){const taskSnap=await getDocs(tasksRef);state.tasks=taskSnap.docs.map(d=>({id:d.id,...d.data()})).filter(t=>t.active!==false).sort((a,b)=>String(a.name).localeCompare(String(b.name),state.lang));if(state.isAdmin){const [entrySnap,memberSnap]=await Promise.all([getDocs(entriesRef),getDocs(membersRef)]);state.allEntries=entrySnap.docs.map(d=>normalizeEntry(d.id,d.data())).sort((a,b)=>dateObj(b.createdAt||b.date)-dateObj(a.createdAt||a.date));state.members=memberSnap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.name||"").localeCompare(String(b.name||"")))}else{const entrySnap=await getDocs(entriesRef);state.mine=entrySnap.docs.map(d=>normalizeEntry(d.id,d.data())).filter(e=>e.uid===state.user.uid).sort((a,b)=>dateObj(b.createdAt||b.date)-dateObj(a.createdAt||a.date))}}
function normalizeEntry(id,e){const base=Number(e.base||0),bonus=Number(e.bonus||0);return{id,...e,base,bonus,total:Number(e.total??(base+bonus)),paid:Boolean(e.paid),status:e.status||"pending"}}
function resolveAvatarId(name){const n=String(name||"").toLowerCase();if(n.includes("наст")||n.includes("nast"))return"nastya";if(n.includes("ром")||n.includes("rom"))return"roma";if(n.includes("волод")||n.includes("grand"))return"grandpa";if(n.includes("ден")||n.includes("den"))return"denys";return"roma"}
function taskParts(t){const raw=String(t?.name||"").trim();const emoji=raw.match(/^\p{Extended_Pictographic}/u)?.[0]||"✓";return{icon:emoji,label:raw.replace(/^\p{Extended_Pictographic}\s*/u,"")}}
function statusLabel(e){if(e.paid)return I18N[state.lang].statusPaid;if(e.status==="approved")return I18N[state.lang].statusApproved;return I18N[state.lang].waiting}
function workHtml(e,admin=false){const p=taskParts({name:e.taskName});return `<div class="work-row"><span class="task-icon">${esc(p.icon)}</span><div class="row-main"><strong>${esc(e.child||state.profile?.name||"")}</strong><small>${esc(p.label)} · ${formatDateTime(e.date)}</small><small>${e.hours?esc(e.hours)+" · ":""}${money(e.total)}</small><span class="work-status ${e.paid?"status-paid":e.status==="approved"?"status-approved":"status-pending"}">${esc(statusLabel(e))}</span>${admin?`<div class="admin-action"><button class="btn btn-secondary" data-confirm-id="${esc(e.id)}" ${e.status==="approved"?"disabled":""}>✓ ${esc(I18N[state.lang].confirm)}</button><button class="btn btn-secondary" data-bonus-id="${esc(e.id)}">＋ ${esc(I18N[state.lang].bonus)}</button><button class="btn ${e.paid?"btn-secondary":"btn-gold"}" data-paid-id="${esc(e.id)}" ${!e.paid&&e.status!=="approved"?"disabled":""}>${e.paid?esc(I18N[state.lang].cancelPaid):esc(I18N[state.lang].paidAction)}</button></div>`:""}</div><div class="row-end">${money(e.total)}</div></div>`}
function taskHtml(t){const p=taskParts(t);return `<button class="task-row" data-task-id="${esc(t.id)}"><span class="task-icon">${esc(p.icon)}</span><span class="row-main"><strong>${esc(p.label)}</strong><small>${esc(t.desc||"")}</small></span><span class="row-end">${money(t.rate)}${t.type==="hour"?"<small>/год</small>":""}</span></button>`}
function renderHome(){const mine=state.mine,total=mine.reduce((s,e)=>s+e.total,0),paid=mine.filter(e=>e.paid).reduce((s,e)=>s+e.total,0);$("homeName").textContent=state.profile?.name||"—";$("homeTotal").textContent=money(total);$("homePaid").textContent=money(paid);$("homeDue").textContent=money(total-paid);$("homeAdminBadge").hidden=!state.isAdmin;$("homeTasks").innerHTML=state.tasks.slice(0,6).map(t=>`<button class="task-tile" data-task-id="${esc(t.id)}"><span class="task-icon">${esc(taskParts(t).icon)}</span><strong>${esc(taskParts(t).label)}</strong><small>${money(t.rate)}${t.type==="hour"?"/год":""}</small></button>`).join("")||`<div class="empty">${esc(I18N[state.lang].noTasks)}</div>`;$("homeRecent").innerHTML=mine.slice(0,4).map(e=>workHtml(e)).join("")||`<div class="empty">${esc(I18N[state.lang].noWork)}</div>`}
function renderTasks(){$("tasksList").innerHTML=state.tasks.map(taskHtml).join("")||`<div class="empty">${esc(I18N[state.lang].noTasks)}</div>`}
function renderHistory(){let list=state.mine;if(state.historyFilter==="pending")list=list.filter(e=>e.status!=="approved"&&!e.paid);if(state.historyFilter==="approved")list=list.filter(e=>e.status==="approved"&&!e.paid);if(state.historyFilter==="paid")list=list.filter(e=>e.paid);$("historyList").innerHTML=list.map(e=>workHtml(e)).join("")||`<div class="empty">${esc(I18N[state.lang].noWork)}</div>`}
function periodEntries(entries){const now=new Date(),start=new Date(now);if(state.reportPeriod==="month")start.setDate(1);if(state.reportPeriod==="quarter"){start.setMonth(Math.floor(now.getMonth()/3)*3,1)}if(state.reportPeriod==="year")start.setMonth(0,1);start.setHours(0,0,0,0);return entries.filter(e=>dateObj(e.date)>=start&&dateObj(e.date)<=now)}
function reportData(){const entries=periodEntries(state.isAdmin?state.allEntries:state.mine),total=entries.reduce((s,e)=>s+e.total,0),paid=entries.filter(e=>e.paid).reduce((s,e)=>s+e.total,0);return{entries,total,paid,due:total-paid}}
function renderReports(){const d=reportData();$("reportTotal").textContent=money(d.total);$("reportPaid").textContent=money(d.paid);$("reportDue").textContent=money(d.due);$("reportCount").textContent=d.entries.length;const groups={};for(const e of d.entries){const key=e.child||"—";groups[key]=(groups[key]||0)+e.total}const max=Math.max(1,...Object.values(groups));$("reportMembers").innerHTML=Object.entries(groups).map(([name,sum])=>`<div class="member-row"><div class="avatar avatar--sm" style="${avatarStyle(resolveAvatarId(name))}"></div><div class="row-main"><strong>${esc(name)}</strong><small>${esc(I18N[state.lang].earned)}: ${money(sum)}</small><div class="progress"><i style="width:${Math.round(sum/max*100)}%"></i></div></div><div class="row-end">${money(sum)}</div></div>`).join("")||`<div class="empty">${esc(I18N[state.lang].noWork)}</div>`}
function renderProfile(){const p=state.profile||{},avatar=p.avatarId||resolveAvatarId(p.name);$("profileAvatar").style=avatarStyle(avatar);$("profileName").textContent=p.name||"—";$("profileRole").textContent=state.isAdmin?I18N[state.lang].admin:I18N[state.lang].members;$("profileEmailValue").textContent=p.email||state.user?.email||"—";$("profileRoleValue").textContent=state.isAdmin?I18N[state.lang].admin:I18N[state.lang].members;const total=state.mine.reduce((s,e)=>s+e.total,0),paid=state.mine.filter(e=>e.paid).reduce((s,e)=>s+e.total,0);$("profileStats").innerHTML=`<div class="profile-stat"><b>${state.mine.length}</b><span>${esc(I18N[state.lang].workLabel)}</span></div><div class="profile-stat"><b>${money(total)}</b><span>${esc(I18N[state.lang].earned)}</span></div><div class="profile-stat"><b>${money(paid)}</b><span>${esc(I18N[state.lang].paid)}</span></div>`;$("avatarPicker").innerHTML=Object.keys(AVATARS).map(id=>`<button class="avatar-option ${id===avatar?"active":""}" data-avatar-id="${id}" aria-label="${esc(AVATARS[id].label)}"><span class="avatar" style="${avatarStyle(id)}"></span></button>`).join("");$("headerProfile").style=avatarStyle(avatar);$("menuUser").innerHTML=`<strong>${esc(p.name||"—")}</strong><small>${esc(p.email||state.user?.email||"")}</small>`}
function renderAdmin(){if(!state.isAdmin)return;const entries=state.allEntries,total=entries.reduce((s,e)=>s+e.total,0),paid=entries.filter(e=>e.paid).reduce((s,e)=>s+e.total,0),pending=entries.filter(e=>!e.paid&&e.status!=="approved").length;$("adminStats").innerHTML=`<div class="stat-card accent"><b>${money(total)}</b><span>${esc(I18N[state.lang].overall)}</span></div><div class="stat-card"><b>${money(paid)}</b><span>${esc(I18N[state.lang].paid)}</span></div><div class="stat-card"><b>${money(total-paid)}</b><span>${esc(I18N[state.lang].toPay)}</span></div><div class="stat-card"><b>${pending}</b><span>${esc(I18N[state.lang].waiting)}</span></div>`;document.querySelectorAll("[data-admin-tab]").forEach(b=>b.classList.toggle("active",b.dataset.adminTab===state.adminTab));if(state.adminTab==="members")renderAdminMembers();if(state.adminTab==="tasks")renderAdminTasks();if(state.adminTab==="works")renderAdminWorks()}
function renderAdminMembers(){$("adminPanel").innerHTML=`<div class="list-card"><div class="section-head"><h2>${esc(I18N[state.lang].members)} (${state.members.length})</h2></div><div class="stack">${state.members.map(m=>`<div class="member-row"><div class="avatar avatar--sm" style="${avatarStyle(m.avatarId||resolveAvatarId(m.name))}"></div><div class="row-main"><strong>${esc(m.name||"—")}</strong><small>${esc(m.email||"")}</small></div><span class="count-badge">${m.role==="admin"?"A":"✓"}</span></div>`).join("")||`<div class="empty">—</div>`}</div></div>`}
function renderAdminTasks(){$("adminPanel").innerHTML=`<div class="list-card"><div class="section-head"><h2>＋ ${esc(I18N[state.lang].tasks)}</h2></div><div class="admin-form"><input id="newTaskName" maxlength="80" placeholder="Назва / Name"><input id="newTaskDesc" maxlength="140" placeholder="Опис / Beschreibung"><select id="newTaskType"><option value="fixed">${state.lang==="de"?"Fester Betrag":"Фіксована сума"}</option><option value="hour">${state.lang==="de"?"Stundenlohn":"Погодинна оплата"}</option></select><input id="newTaskRate" type="number" min="0" step="0.5" value="10"><button id="createTaskButton" class="btn btn-gold">＋ ${state.lang==="de"?"Aufgabe erstellen":"Створити завдання"}</button></div></div><div class="list-card"><div class="stack">${state.tasks.map(taskHtml).join("")}</div></div>`;$("createTaskButton").addEventListener("click",createTask)}
function renderAdminWorks(){$("adminPanel").innerHTML=`<div class="list-card"><div class="stack">${state.allEntries.map(e=>workHtml(e,true)).join("")||`<div class="empty">${esc(I18N[state.lang].noWork)}</div>`}</div></div>`;document.querySelectorAll("[data-confirm-id]").forEach(b=>b.addEventListener("click",()=>approveEntry(b.dataset.confirmId)));document.querySelectorAll("[data-bonus-id]").forEach(b=>b.addEventListener("click",()=>setBonus(b.dataset.bonusId)));document.querySelectorAll("[data-paid-id]").forEach(b=>b.addEventListener("click",()=>togglePaid(b.dataset.paidId)))}
function renderAll(){if(!state.user)return;renderHome();renderTasks();renderHistory();renderReports();renderProfile();renderAdmin();updateNav();}
function updateNav(){document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("active",b.dataset.nav===state.currentScreen))}
function setScreen(id){if(id==="admin"&&!state.isAdmin){showToast(I18N[state.lang].adminOnly);return}state.currentScreen=id;document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$("screen-"+id)?.classList.add("active");updateNav();if(id==="add"&&!state.selectedTask){setScreen("tasks");return}window.scrollTo({top:0,behavior:"smooth"});closeMenu()}
function openTask(id){const task=state.tasks.find(t=>t.id===id);if(!task)return;state.selectedTask=task;const p=taskParts(task);$("addTaskIcon").textContent=p.icon;$("addTaskTitle").textContent=p.label;$("addTaskDescription").textContent=task.desc||"";$("hoursField").hidden=task.type!=="hour";$("hoursInput").value="1";$("workDate").value=todayISO();$("workNote").value="";updateAddTotal();setScreen("add")}
function updateAddTotal(){if(!state.selectedTask)return;const h=state.selectedTask.type==="hour"?Number($("hoursInput").value||0):1;$("addTotal").textContent=money(Number(state.selectedTask.rate||0)*h)}
async function saveWork(){const t=state.selectedTask;if(!t)return;const h=t.type==="hour"?Number($("hoursInput").value||0):null;if(t.type==="hour"&&(!Number.isFinite(h)||h<=0)){showToast(state.lang==="de"?"Stundenzahl eingeben.":"Вкажіть кількість годин.");return}const base=Number(t.rate||0)*(h||1);try{$("saveWork").disabled=true;await addDoc(entriesRef,{uid:state.user.uid,child:state.profile.name,taskId:t.id,taskName:t.name,hours:h,base,bonus:0,total:base,paid:false,status:"pending",date:new Date(`${$("workDate").value||todayISO()}T12:00:00`).toISOString(),createdAt:serverTimestamp()});await refresh();state.selectedTask=null;setScreen("home");showToast((state.lang==="de"?"Arbeit hinzugefügt: ":"Роботу додано: ")+money(base))}catch(e){console.error(e);showToast(state.lang==="de"?"Speichern fehlgeschlagen.":"Не вдалося зберегти роботу.")}finally{$("saveWork").disabled=false}}
async function approveEntry(id){if(!state.isAdmin)return;try{await updateDoc(doc(entriesRef,id),{status:"approved"});await refresh();renderAdmin();showToast(state.lang==="de"?"Bestätigt.":"Роботу підтверджено.")}catch(e){console.error(e);showToast(state.lang==="de"?"Fehler.":"Не вдалося підтвердити.")}}
async function setBonus(id){if(!state.isAdmin)return;const e=state.allEntries.find(x=>x.id===id);if(!e)return;const raw=window.prompt(state.lang==="de"?"Bonus in Euro:":"Бонус у євро:",String(e.bonus||0));if(raw===null)return;const bonus=Number(raw);if(!Number.isFinite(bonus)||bonus<0){showToast(state.lang==="de"?"Ungültiger Betrag.":"Некоректна сума бонусу.");return}try{await updateDoc(doc(entriesRef,id),{bonus,total:Number(e.base||0)+bonus,status:"approved"});await refresh();renderAdmin();showToast(state.lang==="de"?"Bonus gespeichert.":"Бонус збережено.")}catch(e2){console.error(e2);showToast(state.lang==="de"?"Fehler.":"Не вдалося зберегти бонус.")}}
async function togglePaid(id){if(!state.isAdmin)return;const e=state.allEntries.find(x=>x.id===id);if(!e)return;if(!e.paid&&e.status!=="approved"){showToast(state.lang==="de"?"Zuerst bestätigen.":"Спочатку підтвердьте роботу.");return}try{await updateDoc(doc(entriesRef,id),{paid:!e.paid,status:"approved"});await refresh();renderAdmin();showToast(e.paid?(state.lang==="de"?"Zahlung storniert.":"Виплату скасовано."):(state.lang==="de"?"Als ausgezahlt markiert.":"Позначено як виплачено."))}catch(e2){console.error(e2);showToast(state.lang==="de"?"Fehler.":"Не вдалося змінити виплату.")}}
async function createTask(){if(!state.isAdmin)return;const name=$("newTaskName").value.trim(),desc=$("newTaskDesc").value.trim(),type=$("newTaskType").value,rate=Number($("newTaskRate").value);if(!name||!Number.isFinite(rate)||rate<0){showToast(state.lang==="de"?"Name und Betrag eingeben.":"Вкажіть назву та суму.");return}try{await addDoc(tasksRef,{name,desc,type,rate,active:true,createdAt:serverTimestamp(),createdBy:state.user.uid});await refresh();state.adminTab="tasks";renderAdmin();showToast(state.lang==="de"?"Aufgabe erstellt.":"Завдання створено.")}catch(e){console.error(e);showToast(state.lang==="de"?"Fehler.":"Не вдалося створити завдання.")}}
async function refresh(){await ensureDefaultTasks();await loadData();renderAll()}
function openMenu(){$("sideMenu").hidden=false;requestAnimationFrame(()=>$('sideMenu').classList.add("open"))}function closeMenu(){$("sideMenu").classList.remove("open");setTimeout(()=>{$("sideMenu").hidden=true},180)}
function renderOnboarding(){const ids=["roma","nastya","denys","grandpa"];$("onboardingAvatarPicker").innerHTML=ids.map(id=>`<button class="avatar-option ${state.onboardingAvatar===id?"active":""}" data-onboard-avatar="${id}"><span class="avatar" style="${avatarStyle(id)}"></span></button>`).join("");document.querySelectorAll("[data-onboard-avatar]").forEach(b=>b.addEventListener("click",()=>{state.onboardingAvatar=b.dataset.onboardAvatar;renderOnboarding();$("finishAvatarButton").disabled=false}))}
async function finishOnboarding(){if(!state.onboardingAvatar)return;try{await updateDoc(doc(membersRef,state.user.uid),{avatarId:state.onboardingAvatar});state.profile.avatarId=state.onboardingAvatar;$("avatarOnboarding").hidden=true;renderProfile();showToast(state.lang==="de"?"Profil bereit.":"Профіль готовий.")}catch(e){console.error(e);showToast(state.lang==="de"?"Fehler.":"Не вдалося зберегти аватар.")}}
async function saveProfileName(){const name=$("editNameInput").value.trim();if(!name)return;try{await updateProfile(state.user,{displayName:name});await updateDoc(doc(membersRef,state.user.uid),{name});state.profile.name=name;$("profileModal").hidden=true;renderAll();showToast(state.lang==="de"?"Gespeichert.":"Збережено.")}catch(e){console.error(e);showToast(state.lang==="de"?"Fehler.":"Не вдалося зберегти.")}}
function reportText(){const d=reportData(),lines=["PFLEGE — Допомога дідусеві",`${new Date().toLocaleDateString(state.lang==="de"?"de-DE":"uk-UA")}`,`Разом: ${money(d.total)}`,`Виплачено: ${money(d.paid)}`,`До виплати: ${money(d.due)}`,`Робіт: ${d.entries.length}`];if(state.isAdmin){const g={};d.entries.forEach(e=>g[e.child]=(g[e.child]||0)+e.total);for(const [n,v] of Object.entries(g))lines.push(`${n}: ${money(v)}`)}return lines.join("\n")}
async function copyReport(){const text=reportText();try{if(navigator.share){await navigator.share({title:"PFLEGE",text});}else{await navigator.clipboard.writeText(text);showToast(state.lang==="de"?"Bericht kopiert.":"Звіт скопійовано — можна вставити у Viber.")}}catch(e){if(e.name!=="AbortError")try{await navigator.clipboard.writeText(text);showToast(state.lang==="de"?"Bericht kopiert.":"Звіт скопійовано.")}catch{window.prompt("PFLEGE",text)}}}
async function shareApp(){const data={title:"PFLEGE — Допомога дідусеві",text:"PFLEGE",url:"https://volodyka-d0e6f.web.app"};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);showToast(state.lang==="de"?"Link kopiert.":"Посилання скопійовано.")}}catch(e){if(e.name!=="AbortError")showToast(state.lang==="de"?"Link: volodyka-d0e6f.web.app":"Посилання: volodyka-d0e6f.web.app")}}
async function installApp(){if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null}else showToast(I18N[state.lang].installHint)}
function registerSW(){if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js",{scope:"./"}).catch(console.warn)}

$("openRegister").addEventListener("click",()=>authMode("register"));$("backToLogin").addEventListener("click",()=>authMode("login"));$("loginButton").addEventListener("click",login);$("registerButton").addEventListener("click",register);$("loginPassword").addEventListener("keydown",e=>{if(e.key==="Enter")login()});$("registerPassword2").addEventListener("keydown",e=>{if(e.key==="Enter")register()});
$("authLangUa").addEventListener("click",()=>setLanguage("uk"));$("authLangDe").addEventListener("click",()=>setLanguage("de"));$("langUa").addEventListener("click",()=>setLanguage("uk"));$("langDe").addEventListener("click",()=>setLanguage("de"));
$("themeDark").addEventListener("click",()=>{state.theme="dark";localStorage.setItem("pflege-theme","dark");applyTheme()});$("themeLight").addEventListener("click",()=>{state.theme="light";localStorage.setItem("pflege-theme","light");applyTheme()});
$("headerHome").addEventListener("click",()=>setScreen("home"));$("headerProfile").addEventListener("click",()=>setScreen("profile"));$("menuButton").addEventListener("click",openMenu);$("navMenu").addEventListener("click",openMenu);$("closeMenu").addEventListener("click",closeMenu);$("sideBackdrop").addEventListener("click",closeMenu);$("backFromAdd").addEventListener("click",()=>{state.selectedTask=null;setScreen("tasks")});$("backFromShare").addEventListener("click",()=>setScreen("home"));
$("addWorkHome").addEventListener("click",()=>setScreen("tasks"));$("seeAllTasks").addEventListener("click",()=>setScreen("tasks"));$("seeHistory").addEventListener("click",()=>setScreen("history"));document.querySelectorAll("[data-nav]").forEach(b=>b.addEventListener("click",()=>setScreen(b.dataset.nav)));document.querySelectorAll("[data-menu-nav]").forEach(b=>b.addEventListener("click",()=>setScreen(b.dataset.menuNav)));
document.addEventListener("click",e=>{const task=e.target.closest("[data-task-id]");if(task)openTask(task.dataset.taskId);const av=e.target.closest("[data-avatar-id]");if(av)selectAvatar(av.dataset.avatarId)});
function selectAvatar(id){if(!AVATARS[id])return;updateDoc(doc(membersRef,state.user.uid),{avatarId:id}).then(()=>{state.profile.avatarId=id;renderProfile();showToast(state.lang==="de"?"Avatar aktualisiert.":"Аватар оновлено.")}).catch(console.error)}
$("hoursMinus").addEventListener("click",()=>{$("hoursInput").value=Math.max(.25,Number($("hoursInput").value||1)-.25);updateAddTotal()});$("hoursPlus").addEventListener("click",()=>{$("hoursInput").value=Number($("hoursInput").value||1)+.25;updateAddTotal()});$("hoursInput").addEventListener("input",updateAddTotal);$("saveWork").addEventListener("click",saveWork);
document.querySelectorAll("[data-history-filter]").forEach(b=>b.addEventListener("click",()=>{state.historyFilter=b.dataset.historyFilter;document.querySelectorAll("[data-history-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderHistory()}));$("reportPeriod").addEventListener("change",()=>{state.reportPeriod=$("reportPeriod").value;renderReports()});$("copyReport").addEventListener("click",copyReport);$("shareAppButton").addEventListener("click",shareApp);$("installButton").addEventListener("click",installApp);$("settingsShare").addEventListener("click",()=>setScreen("share"));$("settingsInstall").addEventListener("click",installApp);
$("editProfileButton").addEventListener("click",()=>{$("editNameInput").value=state.profile?.name||"";$("profileModal").hidden=false});$("saveProfile").addEventListener("click",saveProfileName);document.querySelectorAll("[data-close-modal]").forEach(x=>x.addEventListener("click",()=>$("profileModal").hidden=true));$("logoutButton").addEventListener("click",()=>signOut(auth));$("finishAvatarButton").addEventListener("click",finishOnboarding);document.querySelectorAll("[data-admin-tab]").forEach(b=>b.addEventListener("click",()=>{state.adminTab=b.dataset.adminTab;renderAdmin()}));
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.installPrompt=e});window.addEventListener("appinstalled",()=>{state.installPrompt=null;showToast(state.lang==="de"?"PFLEGE installiert.":"PFLEGE встановлено на телефоні.")});
applyTheme();applyLanguage();registerSW();
onAuthStateChanged(auth,async user=>{state.user=user;if(!user){$("authView").hidden=false;$("appView").hidden=true;authMode("login");return}try{$("authView").hidden=true;$("appView").hidden=false;state.isAdmin=user.uid===ADMIN_UID;await loadProfile();await refresh();if(!state.profile.avatarId||state.profile.avatarId==="roma"&&(!state.profile.name||state.profile.name!==user.displayName)){state.onboardingAvatar=null;renderOnboarding();$("avatarOnboarding").hidden=false}setScreen("home")}catch(e){console.error(e);showToast(state.lang==="de"?"Firebase-Daten konnten nicht geladen werden.":"Не вдалося завантажити дані Firebase.")}});
